application: stringerbellapp
version: 1 
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /images
  static_dir: images

- url: /audio
  static_dir: audio
  
- url: /cache.manifest
  mime_type: text/cache-manifest 
  static_files: cache.manifest 
  upload: cache.manifest 

- url: /.*
  script: app.py

