// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'text!templates/task.html'], function($, _, Backbone, template) {
    var TaskView, _ref;
    TaskView = (function(_super) {
      __extends(TaskView, _super);

      function TaskView() {
        this.update140 = __bind(this.update140, this);
        this.render = __bind(this.render, this);
        this.events = __bind(this.events, this);
        _ref = TaskView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      TaskView.prototype.tagName = "li";

      TaskView.prototype.className = "task";

      TaskView.prototype.template = _.template(template);

      TaskView.prototype.regexp = new RegExp("#([\\w]*)", "g");

      TaskView.prototype.initialize = function() {
        this.model.on('change', this.render);
        return this.render();
      };

      TaskView.prototype.events = function() {
        var _this = this;
        return {
          'focus textarea': function() {
            return _this.$el.addClass('edit');
          },
          'blur textarea': function() {
            return _this.$el.removeClass('edit');
          },
          'keyup textarea': this.update140
        };
      };

      TaskView.prototype.render = function() {
        var diff, json, text;
        diff = this.model.get('date') - this.model.get('startDate');
        diff = Math.round(diff / 60000);
        text = this.model.get("text");
        text = _.escape(text);
        text = text.replace(this.regexp, '<a class="tag" href="#/tagged/$1" data-tag="$1">#$1</a>');
        json = _.extend(this.model.toJSON(), {
          text: text,
          time: diff,
          date: moment(this.model.get("date")).format("LLLL")
        });
        this.$el.html(this.template(json));
        this.$el.toggleClass('break', this.model.get('isBreak'));
        this.input = this.$el.find('textarea');
        return this;
      };

      TaskView.prototype.tweet = function() {
        var myArray, tags, text;
        text = this.input.val();
        tags = [];
        while ((myArray = this.regexp.exec(text)) !== null) {
          tags.push(myArray[1]);
        }
        console.log(tags);
        this.model.save('text', text);
        return this.model.save('tags', tags);
      };

      TaskView.prototype.update140 = function(e) {
        this.$el.find('.chars').text(140 - this.input.val().length);
        if (e.keyCode === 13 && e.shiftKey !== true) {
          this.tweet();
          return this.$el.next().find('textarea').focus();
        }
      };

      return TaskView;

    })(Backbone.View);
    return TaskView;
  });

}).call(this);
